#!/usr/bin/python3
def raise_exception():
    raise TypeError("An exception has been raised")
